### ISSUE TITLE
popen_spawn_posix hack incompatible with Windows

### ISSUE THREAD

**Issue by SigmaX** [AureumChaos/LEAP#237]
While looking into #219 I realized that the "Python 3.9 workaround" we have been using for dask (following [this discussion](https://github.com/dask/distributed/issues/4168)) is platform dependent:

![image](https://user-images.githubusercontent.com/313154/209362166-278bfab1-7d3b-4f08-b643-76598e5593eb.png)

Running this on windows results in `AttributeError: module 'os' has not attribute WNOHANG`

**Comment by SigmaX** [comment]
I'm not sure if this workaround is still necessary for recent version of dask.  Seems to run find on Windows with Python 3.10 if I comment it out.  Haven't tested on Linux or 3.9 yet.

**Comment by SigmaX** [comment]
I've set up on my local `pyenv` (see [README](https://github.com/pyenv/pyenv)) so I can switch back to 3.9 and test whether the workaround is still necessary.

**Comment by SigmaX** [comment]
Numpy doesn't install properly when I switch to 3.9 with `pyenv`.

```
pyenv global pypy3.9-7.3.10
pip -m venv ./venv39
source venv39/bin/activate
pip install -e
```

Results in 
```
$ python -m pip install -e .
Obtaining file:///home/eric/repos/LEAP
  Preparing metadata (setup.py) ... done
Collecting dask[complete]
  Using cached dask-2022.12.1-py3-none-any.whl (1.1 MB)
Collecting distributed
  Using cached distributed-2022.12.1-py3-none-any.whl (930 kB)
Collecting docopt
  Using cached docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Collecting matplotlib
  Using cached matplotlib-3.6.2-pp39-pypy39_pp73-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.4 MB)
Collecting networkx
  Using cached networkx-2.8.8-py3-none-any.whl (2.0 MB)
Collecting numpy
  Using cached numpy-1.24.1-pp39-pypy39_pp73-linux_x86_64.whl
Collecting pandas
  Using cached pandas-1.5.2.tar.gz (5.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-build-env-va0y1pjy/overlay/lib/pypy3.9/site-packages/numpy/core/__init__.py", line 23, in <module>
          from . import multiarray
        File "/tmp/pip-build-env-va0y1pjy/overlay/lib/pypy3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>
          from . import overrides
        File "/tmp/pip-build-env-va0y1pjy/overlay/lib/pypy3.9/site-packages/numpy/core/overrides.py", line 6, in <module>
          from numpy.core._multiarray_umath import (
      ImportError: /tmp/pip-build-env-va0y1pjy/overlay/lib/pypy3.9/site-packages/numpy/core/_multiarray_umath.pypy39-pp73-x86_64-linux-gnu.so: undefined symbol: cblas_sgemm
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/eric/repos/LEAP/venv39/lib/pypy3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/eric/repos/LEAP/venv39/lib/pypy3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/eric/repos/LEAP/venv39/lib/pypy3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-va0y1pjy/overlay/lib/pypy3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-va0y1pjy/overlay/lib/pypy3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-va0y1pjy/overlay/lib/pypy3.9/site-packages/setuptools/build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-va0y1pjy/overlay/lib/pypy3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 18, in <module>
        File "/tmp/pip-build-env-va0y1pjy/overlay/lib/pypy3.9/site-packages/numpy/__init__.py", line 141, in <module>
          from . import core
        File "/tmp/pip-build-env-va0y1pjy/overlay/lib/pypy3.9/site-packages/numpy/core/__init__.py", line 49, in <module>
          raise ImportError(msg)
      ImportError:
      
      IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
      
      Importing the numpy C-extensions failed. This error can happen for
      many reasons, often due to issues with your setup or how NumPy was
      installed.
      
      We have compiled some common reasons and troubleshooting tips at:
      
          https://numpy.org/devdocs/user/troubleshooting-importerror.html
      
      Please note and check the following:
      
        * The Python version is: Python3.9 from "/home/eric/repos/LEAP/venv39/bin/python"
        * The NumPy version is: "1.24.1"
      
      and make sure that they are the versions you expect.
      Please carefully study the documentation linked above for further help.
      
      Original error was: /tmp/pip-build-env-va0y1pjy/overlay/lib/pypy3.9/site-packages/numpy/core/_multiarray_umath.pypy39-pp73-x86_64-linux-gnu.so: undefined symbol: cblas_sgemm
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.
You should consider upgrading via the '/home/eric/repos/LEAP/venv39/bin/python -m pip install --upgrade pip' command.
```

Same results if I upgrade `pip`, and if I run `pip` through` python -m pip`.

**Comment by SigmaX** [comment]
Seeing if building `numpy` from source makes a difference (as suggested [here](https://github.com/piwheels/packages/issues/9)):

```
$ pip install numpy --upgrade --no-binary :all:
```
