### ISSUE TITLE
"Exception: Tried sending message after closing" with synchronous.eval_pool()

### ISSUE THREAD

**Issue by SigmaX** [AureumChaos/LEAP#77]
I tried to mimic `examples/simple_sync_distributed.py`, but using `generational_ea` instead of a custom loop.

Dask crashes and burns with the output below.  @piprrr --- any idea what causes it?  The only logical difference I can see between my code and the example is that `generational_ea` evaluates the initial population sequentially.

```python
"""test.py: MWE for synchronous distribution."""
import sys

from dask.distributed import Client

from leap_ec import individual, decoder, problem, representation, ops, probe
from leap_ec.context import context
from leap_ec.real_rep import initializers, ops as real_ops, problems as real_problems
from leap_ec.distributed import synchronous
from leap_ec.algorithm import generational_ea


if __name__ == '__main__':
    gens = 1000
    pop_size = 2
    with Client() as dask_client:
        ea = generational_ea(generations=gens, pop_size=pop_size,
                            problem=real_problems.SpheroidProblem(),

                            representation=representation.Representation(
                                decoder=decoder.IdentityDecoder(),
                                initialize=initializers.create_real_vector(bounds=[(-1, 1)]*100)
                            ),

                            pipeline=[
                                ops.tournament_selection,
                                ops.clone,
                                real_ops.mutate_gaussian(
                                    std=0.1, hard_bounds=(-1, 1)),

                                # Works fine with the sequential operators
                                #ops.evaluate,
                                #ops.pool(size=pop_size),

                                # Crashes when I use this one
                                synchronous.eval_pool(client=dask_client, size=pop_size),

                                probe.FitnessStatsCSVProbe(context, stream=sys.stdout)
                            ])
    list(ea)

```
And the output:

```
(venv) [eric@alfred LEAP]$ python examples/test.py 
step, bsf, mean_fitness, std_fitness, min_fitness, max_fitness
Traceback (most recent call last):
  File "examples/test.py", line 41, in <module>
    list(ea)
  File "/home/eric/repos/LEAP/leap_ec/algorithm.py", line 116, in generational_ea
    offspring = pipe(parents, *pipeline)
  File "/home/eric/repos/LEAP/venv/lib/python3.8/site-packages/toolz/functoolz.py", line 634, in pipe
    data = func(data)
  File "/home/eric/repos/LEAP/venv/lib/python3.8/site-packages/toolz/functoolz.py", line 303, in __call__
    return self._partial(*args, **kwargs)
  File "/home/eric/repos/LEAP/leap_ec/distributed/synchronous.py", line 75, in eval_pool
    evaluated_offspring = eval_population(unevaluated_offspring, client,
  File "/home/eric/repos/LEAP/leap_ec/distributed/synchronous.py", line 35, in eval_population
    worker_futures = client.map(evaluate(context=context), population)
  File "/home/eric/repos/LEAP/venv/lib/python3.8/site-packages/distributed/client.py", line 1769, in map
    futures = self._graph_to_futures(
  File "/home/eric/repos/LEAP/venv/lib/python3.8/site-packages/distributed/client.py", line 2587, in _graph_to_futures
    self._send_to_scheduler(
  File "/home/eric/repos/LEAP/venv/lib/python3.8/site-packages/distributed/client.py", line 966, in _send_to_scheduler
    raise Exception(
Exception: Tried sending message after closing.  Status: closed
Message: {'op': 'update-graph', 'tasks': {'evaluate-f16181afd0d977df2effcf744efc6577': {'function': b"\x80\x05\x95\x1e\x05\x00\x00\x00\x00\x00\x00\x8c\x0ftoolz.functoolz\x94\x8c\x0e_restore_curry\x94\x93\x94(h\x00\x8c\x05curry\x94\x93\x94\x8c%leap_ec.distributed.evaluate:evaluate\x94)}\x94\x8c\x07context\x94}\x94\x8c\x04leap\x94}\x94(\x8c\x0bdistributed\x94}\x94\x8c\nnon_viable\x94K\x00s\x8c\ngeneration\x94K\x00uss(\x8c\x07__doc__\x94X\xee\x03\x00\x00 concurrently evaluate the given individual\n\n    This is what's invoked on each dask worker to evaluate each individual.\n\n    We log the start and end times for evaluation.\n\n    An individual is viable if an exception is NOT thrown, else it is NOT a\n    viable individual.  If not viable, we increment the context['leap'][\n    'distributed']['non_viable'] count to track such instances.\n\n    This function sets:\n\n    individual.start_eval_time has the time() of when evaluation started.\n    individual.stop_eval_time has the time() of when evaluation finished.\n    individual.is_viable is True if viable, else False\n    individual.exception will be assigned any raised exceptions\n    individual.fitness will be NaN if not viable, else the calculated fitness\n    individual.hostname is the name of the host on which this individual was\n    evaluated\n    individual.pid is the process ID associated with evaluating the individual\n\n    :param individual: to be evaluated\n    :return: evaluated individual\n    \x94\x86\x94\x8c\x08__name__\x94\x8c\x08evaluate\x94\x86\x94\x8c\n__module__\x94\x8c\x1cleap_ec.distributed.evaluate\x94\x86\x94\x8c\x0c__qualname__\x94h\x13\x86\x94\x8c\x11_has_unknown_args\x94N\x86\x94t\x94\x89t\x94R\x94.", 'args': b"\x80\x05\x95D\x04\x00\x00\x00\x00\x00\x00\x8c\x12leap_ec.individual\x94\x8c\nIndividual\x94\x93\x94)\x81\x94}\x94(\x8c\x06genome\x94]\x94(G?\xd4X\xf4\xcch\xd9\xf6G?\xed\xabi\xf4\xa7\x0f\xdaG\xbf\xe1J(\x14~\x95\x9cG\xbf\xc8\x85\xf8\xcf\x81\x8cbG?\xe5A\x85=|\xa9dG?\xbc\x12\x88\xf4\x04\xe8\x0fG?\xe6\xf5w|\xb1suG?\xda\x04\x1a42\r\xedG\xbf\xed\x8e\x89!j\xf5\xe4K\x01G\xbf\xd74ZQ$\x98*G\xbf\xda\xbc\xee\xe1@\xa9`G\xbf\xea\xce\xb3\xac\xd8\x8b\xf6G?\xe3\xa9\x05&\xe26QG\xbf\xe1\x9f\x8c\x86^\xcdfG\xbf\xa3\x80\xd1\xe6\x94\xb0TG\xbf\xe9\x1d#j\xc5\x17\xf0G\xbf\xee\x91\x8f\x9aBC\xc1G?\xd1\xae\x9d;\xbbN\x89G?\xe1\xa04\x1a\x91\x1e\x08G\xbf\xe1\xfc\x91\xa2\xa8\xfb\xa8G?\x95?\xe5_0\xf3lG\xbf\xa3\x1d\xf6\x9a\xdek|G?\xef\xf2\x90\xca\x88\xfesG\xbfvy\xdf\xaa#\x90PG?\xe9p[<m\xc7\xc6G\xbf\xe9\x01i\xd8EI\x8eG?\xe3b>\x96\x9eP\xbfG\xbf\xec/\x16\x11b\x9c\xabG?\xc0\\m\x90\x11\x05`G?\xe8\xde\xcddT~{G?\x9f\xb2Rz\xb0\xe5^G\xbf\xd0P2\xb4\xa2\xffSG?\xe9\xac\xcb\xe4\x8f\x18\x06G?\xc1\x86\x00\xe9=\xc4\xffG?\xe5\xed;\x97\xc0.\xceG\xbf\xe9l0T\x15\xdd[G\xbf\xe1\xad;V\xb1\xbdTG?\xdev\x84J\x0eD\x95G\xbf\xd4\xfe\x11\xf0\xc2'\xb8G\xbf\xeeq\x8f\x15\xb4\x1e\x0bG\xbf\xe0\x95H\x88\\\xf73G?\xbe||\xe8\xfa\xf5bG\xbf\xe9\x0f*5\x9e`(G\xbf\xe0\xb9\xb6\x9d\xe7\xc3KG\xbf\xc3\x16\x16\xfbk\xf2\xf4G\xbf\xdf\x8bv\x90\xec\xea\xc0G?\x89\x12\x08Z\x12V\x90G?\xd8<\r\xe3\xed8sG\xbf\xe6W(+[\xb5\xdaG\xbf\xd8;'4\x91*\x98G?\xe5s\xe0\xe8\x04\xcf\xffG\xbf\xe0\xbb\xea3\xfe\xfb\xdeG?\xcep\x8c\x1b-\xff0G?\xe0i\xba_8\x1c\xe4G?\xc5\xba\xf5\n\xda\xa2\xc0G?\xee&\xd5\xf1Y\xba\xcbG?\xbb\x11\xfeQMB\x0eG\xbf\xe3Z\x84\xc2\x98\xc7BG?\xd1\xfcr\x07\xd7\xe1gG\xbf\xd7\xd7\xe6\xeb\xaa\xeb\\G?\xc6\xbb\xd3\xed\xa9\xb9$G\xbf\xee;\x0b\xb0\xaa\xdaOG?\xe81\x10\xcd\x1c\xa52G\xbf\xdd5\xe0\xd1\xb0e\xf3G\xbf\xe8E:\xc9\xd45#G\xbf\xe4\x02\xa2\x89@-\x05G\xbf\xccM\xaa\xda\t=\xa7G?\xe6\r\x8e$\xe0\x80\xeaG?\xe4-z\x80+v\x8eG\xbfm\x17s\xf3\x83]\xe0G\xbf\xad\xc2\xac\x18IW\x00G\xbf\xde\xb9\xadSn\xf1\xd5G?\xcf1g\xabo\x97lG?\xe6\xd4n\xdc\xc0\xdckG?\xa5[#\x1d\xf5\x1b\x12G\xbf\xe5\xeei^\xc4\xf2\x88G?\xe4\xa01\xd6\xe5\xf6\x06G?\xd9\x85{\xb6\xa5\x01\x10G?\xe89\xe1\xc2`\xa5MG\xbf\xc8s]q?\xd3\x05G?\xe6\x1b\xf5l\x86\x06;G?\xa3~\xe7\xbe\xec\x99bG\xbf\xebY\x18\x1d\xe91WG?\xdeG7l\xf5\xe1\xffG\xbf\xc2h@\xa06\x8f\xf0G\xbf\x9b]h\xf9\xebJ\x08G\xbf\xd6/SMc\xbd\xbeG?\xdf\xd4\x84!4\x0e\xcaG\xbf\xecegG\xcb\xcc\xefG?\xc0r\xb9\xc5g\x92EG?\x91\x02\xad\xb5\xb6\x00\xd0G\xbf\xe5a!\xd0\xce\x7f\xf5G\xbf\xd9\xb1'&\xa3!|G?\xce\x11\xc9q\xe0\x80\xe0G?\xdb\x1e\x86\xd6\xb3\x8e\xf9G?\xa1\\\xd2\x94\xa1\xafXG?\xcb4\xc2\x043e\x80G?\xdfk\x04\xcc,\xe6\tG\xbf\xda\xdf\xca4\x0b\\%e\x8c\x07problem\x94\x8c\x19leap_ec.real_rep.problems\x94\x8c\x0fSpheroidProblem\x94\x93\x94)\x81\x94}\x94\x8c\x08maximize\x94\x89sb\x8c\x07decoder\x94\x8c\x0fleap_ec.decoder\x94\x8c\x0fIdentityDecoder\x94\x93\x94)\x81\x94\x8c\x07fitness\x94Nub\x85\x94."}, 'evaluate-2d17de849afd858d51a5046f35a7f8e7': {'function': b"\x80\x05\x95\x1e\x05\x00\x00\x00\x00\x00\x00\x8c\x0ftoolz.functoolz\x94\x8c\x0e_restore_curry\x94\x93\x94(h\x00\x8c\x05curry\x94\x93\x94\x8c%leap_ec.distributed.evaluate:evaluate\x94)}\x94\x8c\x07context\x94}\x94\x8c\x04leap\x94}\x94(\x8c\x0bdistributed\x94}\x94\x8c\nnon_viable\x94K\x00s\x8c\ngeneration\x94K\x00uss(\x8c\x07__doc__\x94X\xee\x03\x00\x00 concurrently evaluate the given individual\n\n    This is what's invoked on each dask worker to evaluate each individual.\n\n    We log the start and end times for evaluation.\n\n    An individual is viable if an exception is NOT thrown, else it is NOT a\n    viable individual.  If not viable, we increment the context['leap'][\n    'distributed']['non_viable'] count to track such instances.\n\n    This function sets:\n\n    individual.start_eval_time has the time() of when evaluation started.\n    individual.stop_eval_time has the time() of when evaluation finished.\n    individual.is_viable is True if viable, else False\n    individual.exception will be assigned any raised exceptions\n    individual.fitness will be NaN if not viable, else the calculated fitness\n    individual.hostname is the name of the host on which this individual was\n    evaluated\n    individual.pid is the process ID associated with evaluating the individual\n\n    :param individual: to be evaluated\n    :return: evaluated individual\n    \x94\x86\x94\x8c\x08__name__\x94\x8c\x08evaluate\x94\x86\x94\x8c\n__module__\x94\x8c\x1cleap_ec.distributed.evaluate\x94\x86\x94\x8c\x0c__qualname__\x94h\x13\x86\x94\x8c\x11_has_unknown_args\x94N\x86\x94t\x94\x89t\x94R\x94.", 'args': b'\x80\x05\x952\x04\x00\x00\x00\x00\x00\x00\x8c\x12leap_ec.individual\x94\x8c\nIndividual\x94\x93\x94)\x81\x94}\x94(\x8c\x06genome\x94]\x94(G?\x95\x81K\xfe\'<`G\xbf\xe5\x81q\xfc\xe7\x98\xc0G?\xd1`<Q\xf5\x9b\x82G\xbf\xde\xbc\xd8~\xa5\xdckG\xbf\xd3\xee\xcc\xf0\xf8\x8f\xfbG?\xb5\xfa\x1e\xdc\xc8\x88\xb0G\xbf\xe6\xb3&;\x89\t\xfaG?\xebG\x1a[\xbeZ\x0bG\xbf\xc3*\xf7R\xd2\x13}G?\xecc]\\\xed\xe8\xe9G\xbf\xd5\xd5D\t\xedp\xd2G\xbf\xea\xd1\xdb83\xf2\xf0G?\xde]K\x88\x03 \x8bG?\xd9.\x0e^\xcd\xb7TG?\xe3i5\x9b\x12E\x1cG\xbf\xe3Njr<\xd6gG\xbf\xc2\xc0t\xf7\xcb\xb7pK\x01G\xbf\xe0j\xe6\xd8-\x1dRG\xbf\xd0\xd3I\xee\x1b\xed\x82G?\xe7%\x97.\xfe\xad\x03G\xbf\xe1g\xca\xebB\x07\xa5G?\xe4q\x1d\xc5\xcc\xb2@G?\xdd|J\xaa\xa3\x1b\xc0G\xbf\xc1f\x1aX\x8cyRG?\xbc\xa5\x1e\xc1\xeb \x00G\xbf\xd8\xd2\xbf\xff\'\xbdNG\xbf\xe4\xb6\xed\xfa\xbd[\x88G?\xe7eB\x9f6X\x99G\xbf\xe7\xa0\xe7Vc\xc1iG?\xeb1\xf0\xc9m\x9a]G?\xec\x8b\xfaU!\xad\xafG\xbf\xe1\xff:\xda\xa4+\xb7G\xbf\xc1\x9e\xb5:\xdb\xf2\x9aG\xbf\xce`Xe\xce\xf5\x00G?\xe6\xb7Qb\xc0\xe2\xbeG?\xea\x1bi\x0b\xdb\r\x90G?\xc1\xf5t\xf9\x91\xce+G?\x81\xd1(\xe8\x91\xf7\xd0G\xbf\xda\xe0\x18;\xffK\x1eG\xbf\xd3s\x02\x95\x00O\x93G?\xe9\x1d\r[\xcf@\xbfG\xbf\xe2t\x9c\xca\x96\xbc\xa4G?\xe4e\x8e\xc2\x9a)\x9eG?\xe0Z\x91<=\x04vG?\xd6\x13ch\x1f\xf6\xf6G?\xe4Z-\xb6\x19\x82\x0bG\xbf\xe7.\x11\x8d\x87\x0c\xbfG?\xe2\xb7\xa2\x93\x1b\xfe\xd7K\x01G?\xe6\x8a\xa8l\xe8\x97jG\xbf\xaf\xff\xd4\xc0\x95clG?\xda\x7f\xce\x9fs\xb4\xa3G?\xea\x94t\xd5\xa4\xd6\xcfG?\xdf\x12\x93`\xe8\xa2\xf0G?\xa8%;\xd6\x1f\xd2xG\xbf\xe7/\xc9\xbd\x8d"@G?\xd7\xd8\x83^\xf0?.J\xff\xff\xff\xffG\xbf\xd6\xcc\xfa`\xae\xea@G\xbf\xee\t\xf5(\xa2\xe9ZG?\xef^\x148[\xe6\xa4G?\xde\xf0z\tL,\x92G\xbf\xea\x88#`w\x8c:G\xbf\xb606\xc5R\x83\xb6G?\xeb\x9f\x88\x898\rLG?\xe4).\xff\xfaX=G\xbf\xe3*$\t#,\x7fG?\xa6\x837g\xb2\xac\xfdG\xbf\xe0\xee\xd3\xdc\xc2\xbfnG\xbf\xde\xc7n"\xf0b\xdaG\xbf\xd6f\xfb\xbd\xb4\x1b.G\xbf\xcdo\x8c\x84TQ\xecG\xbf\xe9\'(\xf6>\xc5\xb8G?\xd9\x1e9Q\xe5\xbc\xe9G?\xac\x1f\xe6|\xb2\xffTG?\xe0S\'\xd9a\xd6=G\xbf\xdf]+\xca\x9ci\xb0G\xbf\xe2\xc1\xe7\x01s^]G\xbf\xe6#\x8d\xec\x1cR_G?\xc2\x98\x08\xb7N\xcd\x0bG?\xec\xf7\x06U\x08"<G?\xd5\xa8p\xc3\xbe\xe8^G?\xe6\xa5;\xb8\x1f\xd2\x16G\xbf\xea=\x18\xaf\xe4\xcbyG\xbf\xe1b\x14\xe8\x10h\xeeG?\xc2i\xb2\xbfC\xc2\x86G?\xd1\xa3\xbe\xea\xbd\xa4;G\xbf\xd5\x93\xa7\xd3+\x96NG?\xe4~\x9b}\xd1\xe9\x82G?\xb3\x04\xa8g\xb5\xfe0G\xbf\xd3:b\xa0\x89\xcb\xf5G?\xe8\xceJcINFG\xbf\xe1_/\x92!\\\xb8G?\xd8\xb5\xd8\xdc\xaf\xf8\xfcG\xbf\xda\x08q\xe6\xe8}\xe5G?\xe9Z<,I\xd8\xedG?\xe1cH\x9cs\t\xf3G?\xe7#\r(\x88\xc3\xacK\x01e\x8c\x07problem\x94\x8c\x19leap_ec.real_rep.problems\x94\x8c\x0fSpheroidProblem\x94\x93\x94)\x81\x94}\x94\x8c\x08maximize\x94\x89sb\x8c\x07decoder\x94\x8c\x0fleap_ec.decoder\x94\x8c\x0fIdentityDecoder\x94\x93\x94)\x81\x94\x8c\x07fitness\x94Nub\x85\x94.'}}, 'dependencies': {}, 'keys': ['evaluate-f16181afd0d977df2effcf744efc6577', 'evaluate-2d17de849afd858d51a5046f35a7f8e7'], 'restrictions': {}, 'loose_restrictions': [], 'priority': {'evaluate-f16181afd0d977df2effcf744efc6577': 0, 'evaluate-2d17de849afd858d51a5046f35a7f8e7': 1}, 'user_priority': 0, 'resources': None, 'submitting_task': None, 'retries': None, 'fifo_timeout': '100 ms', 'actors': False}
```

**Comment by SigmaX** [comment]
Resolved.  I forgot that the out monolothic `generational_ea` algorithm evaluates *lazily* when the iterator it returns is pulsed.

I just needed to indent `list(ea)` one level so it runs inside the `with` block instead of outside of it.
